name: Rust Semver Checks
on:
  # Run source-level checks in the unprivileged pull request context.
  pull_request:
    branches:
      - "**"

env:
  LLVM_MAIN_VERSION: "21"
  LLVM_VERSION: "21.1"
  LLVM_FEATURE_NAME: "21-1"

jobs:
  # Check if changes were made to the relevant files.
  # Always returns true if running on the default branch, to ensure all changes are thoroughly checked.
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      rust: ${{ steps.filter.outputs.rust }}
      python: ${{ steps.filter.outputs.python }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check-changes
        id: filter

  rs-semver-checks:
    runs-on: ubuntu-latest
    needs: [changes]
    if: ${{ needs.changes.outputs.rust == 'true' }}
    permissions:
      contents: read
    steps:
      - name: Install LLVM and Clang
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository 'deb https://apt.llvm.org/noble/    llvm-toolchain-noble-${{ env.LLVM_MAIN_VERSION }}   main'
          sudo apt update
          sudo apt install llvm-${{ env.LLVM_MAIN_VERSION }} libpolly-${{ env.LLVM_MAIN_VERSION }}-dev
      - name: Run Rust checks
        uses: quantinuum/hugrverse-actions/rs-semver-checks@9ee45163d8656eb06d513cb39b77d186f86789f6
